name: iclinix
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.5.4

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_lints: ^4.0.0
  get: ^4.6.6
  pin_code_fields: ^8.0.1
  shared_preferences: ^2.3.2
  flutter_typeahead: ^5.2.0
  flutter_rating_bar: ^4.0.1
  intl: ^0.19.0
  http: ^1.2.2
  file_picker: ^8.1.2
  image_picker: ^1.1.2
  fluttertoast: ^8.2.8
  cached_network_image: ^3.4.1
  shimmer: ^2.0.0
  animated_custom_dropdown: ^3.1.1
  flutter_slide_drawer: ^1.0.3
  url_launcher: ^6.3.1
  flutter_widget_from_html: ^0.15.3
  html: ^0.15.4
  syncfusion_flutter_charts: ^27.1.56
#  flutter_html_to_pdf: ^0.6.1
  lottie: ^3.1.3
  easy_image_viewer: ^1.5.0
  permission_handler: ^10.2.0
  path_provider: ^2.0.14
  #  awesome_notifications: ^0.10.0
  flutter_local_notifications: ^18.0.1
  razorpay_flutter: ^1.3.7
  pdf: ^3.10.5
  printing: ^5.11.0
  firebase_messaging: ^15.1.5
  youtube_player_flutter: ^9.1.1
  dio: ^5.7.0
  open_file: ^3.5.10


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
      - assets/images/
      - assets/icons/

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/font/OpenSans-Bold.ttf
          weight: 700
        - asset: assets/font/OpenSans-ExtraBold.ttf
          weight: 800
        - asset: assets/font/OpenSans-Medium.ttf
          weight: 500
        - asset: assets/font/OpenSans-Regular.ttf
          weight: 400
        - asset: assets/font/OpenSans-SemiBold.ttf
          weight: 600